apiVersion: batch/v1
kind: Job
metadata:
  name: v1
spec:
  template:
    spec:
      hostPID: true
      hostNetwork: true
      containers:
      - name: check
        image: mohanvamsi06/fyp:v0.0.1
        imagePullPolicy: Always
        volumeMounts:
        - name: kubernetes
          mountPath: /etc/kubernetes
          readOnly: true
        - name: cni
          mountPath: /etc/cni/net.d
          readOnly: true
        - name: lib-cni
          mountPath: /var/lib/cni
          readOnly: true          
        - name: etcd
          mountPath: /var/lib/etcd
          readOnly: true
        - name: output
          mountPath: /output
      restartPolicy: Never
      volumes:
      - name: kubernetes
        hostPath:
          path: /etc/kubernetes
      - name: cni
        hostPath: 
          path: /etc/cni/net.d
      - name: lib-cni
        hostPath: 
          path: /var/lib/cni
      - name: etcd
        hostPath:
          path: /var/lib/etcd
      - name: output
        hostPath:
          path: /var/tmp/results
          type: DirectoryOrCreate
