apiVersion: cilium.io/v1alpha1
kind: TracingPolicy
metadata:
  name: "bpf-monitoring"
spec:
  tracepoints:
  - subsystem: "syscalls"
    event: "sys_enter_bpf"
    args:
    - index: 0
      type: "int"       # BPF command
    - index: 1
      type: "unsigned long"  # Attributes pointer
    - index: 2
      type: "unsigned int"   # Size
    selectors:
    # Exclude legitimate eBPF users
    - matchBinaries:
      - operator: "NotIn"
        values:
        - "/usr/bin/tetragon"
        - "/usr/lib/systemd/systemd"
        - "/usr/bin/containerd"
        - "/usr/bin/dockerd"
        - "/usr/sbin/bpftool"
