apiVersion: cilium.io/v1alpha1
kind: TracingPolicy
metadata:
  name: "chown-monitoring"
spec:
  tracepoints:
  - subsystem: "syscalls"
    event: "sys_enter_fchownat"
    selectors:
    - matchActions:
      - action: Post
  - subsystem: "syscalls"
    event: "sys_enter_chown"
    selectors:
    - matchActions:
      - action: Post
