apiVersion: cilium.io/v1alpha1
kind: TracingPolicy
metadata:
  name: "chmod-monitoring"
spec:
  tracepoints:
  - subsystem: "syscalls"
    event: "sys_enter_fchmodat"
    selectors:
    - matchActions:
      - action: Post
  - subsystem: "syscalls"
    event: "sys_enter_chmod"
    selectors:
    - matchActions:
      - action: Post
