apiVersion: cilium.io/v1alpha1
kind: TracingPolicy
metadata:
  name: "delete-module-monitoring"
spec:
  tracepoints:
  - subsystem: "syscalls"
    event: "sys_enter_delete_module"
    args:
    - index: 0
      type: "string"    # Module name
    - index: 1
      type: "int"       # Flags
    selectors:
    # Alert on security module removal
    - matchArgs:
      - index: 0
        operator: "In"
        values:
        - "apparmor"
        - "selinux"
        - "tetragon"
        - "audit"
        - "ip_tables"
