apiVersion: cilium.io/v1alpha1
kind: TracingPolicy
metadata:
  name: "file-open-monitoring"
spec:
  kprobes:
  - call: "security_file_open"
    syscall: false
    args:
    - index: 0
      type: "file"
    selectors:
    # Only monitor sensitive files
    - matchArgs:
      - index: 0
        operator: "Prefix"
        values:
        - "/etc/shadow"
        - "/etc/passwd"
        - "/root/.ssh/"
        - "/home/*/.ssh/"
