apiVersion: cilium.io/v1alpha1
kind: TracingPolicy
metadata:
  name: rt-security-inode-unlink-19
spec:
  kprobes:
  - call: security_inode_unlink
    syscall: true
    matchActions:
    - action: Post
