FROM python:3.12-slim

RUN apt-get update && apt-get install -y --no-install-recommends \
    procps coreutils findutils grep \
    && rm -rf /var/lib/apt/lists/*
    
WORKDIR /app

COPY . . 

RUN pip install -r requirements.txt

COPY main.py . 

CMD ["python3", "main.py"]
